// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

#include <iostream>

using namespace std;

int main(){
    
    int first = 1;
    int second = 2;
    int third;
    int sum = 0;
    while(sum < 4000000){ 
        third = first + second;
        first = second;
        second = third;
        if (third % 2 == 0){
            sum += third;
        }
        
    }
    cout << sum + 2; // 2 is the first even term

    return 0; 
}
